import sys
import json
import os
import pandas as pd
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

def generate_report(json_in, excel_out, report_type, start_date, end_date):
    # Ensure the input JSON file exists
    if not os.path.exists(json_in):
        print(f"Error: Input JSON file missing: {json_in}")
        sys.exit(1)

    # Load the temporary JSON data generated by PHP
    with open(json_in, 'r') as f:
        data = json.load(f)
    
    # Load into a DataFrame
    df = pd.DataFrame(data)
    
    # Structure empty files gracefully to prevent crashes
    if df.empty:
        df = pd.DataFrame(columns=[
            'customer_name', 'check_in_time', 'check_out_time', 'pax', 
            'adults', 'seniors', 'children', 'accommodation', 'overnight', 'payment_method'
            'payment_status', 'total_amount'
        ])
    
    # Rename columns for a clean presentation
    df.rename(columns={
        'customer_name': 'Customer Name',
        'check_in_time': 'Check-In',
        'check_out_time': 'Check-Out',
        'pax': 'Total Pax',
        'adults': 'Adults',
        'seniors': 'Seniors',
        'children': 'Children',
        'accommodation': 'Accommodation',
        'overnight': 'Overnight',
        'payment_status': 'Status',
        'payment_method': 'Cash',
        'total_amount': 'Total Payment'
    }, inplace=True)

    # Handle missing check-outs
    df['Check-Out'] = df['Check-Out'].fillna('Active')
    
    # Ensure numerical columns are handled correctly
    num_cols = ['Total Pax', 'Adults', 'Seniors', 'Children']
    for col in num_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype(int)
            
    df['Total Payment'] = pd.to_numeric(df['Total Payment'], errors='coerce').fillna(0.0)

    # Ensure output directory exists before writing
    os.makedirs(os.path.dirname(excel_out), exist_ok=True)

    # Write to Excel using the openpyxl engine
    with pd.ExcelWriter(excel_out, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Report Data', startrow=2)
        
        workbook = writer.book
        worksheet = writer.sheets['Report Data']
        
        # --- DESIGN PALETTE ---
        primary_color = "1E3A8A"      # Deep Navy Blue
        zebra_color = "F3F4F6"        # Very Light Gray
        white = "FFFFFF"
        
        # Fonts
        title_font = Font(name="Arial", size=15, bold=True, color=primary_color)
        header_font = Font(name="Arial", size=11, bold=True, color=white)
        data_font = Font(name="Arial", size=10)
        total_font = Font(name="Arial", size=11, bold=True)
        
        # Fills
        header_fill = PatternFill(start_color=primary_color, end_color=primary_color, fill_type="solid")
        zebra_fill = PatternFill(start_color=zebra_color, end_color=zebra_color, fill_type="solid")
        
        # Borders
        thin_side = Side(border_style="thin", color="D1D5DB")
        double_side = Side(border_style="double", color="1E3A8A")
        
        data_border = Border(left=thin_side, right=thin_side, top=thin_side, bottom=thin_side)
        total_border = Border(top=thin_side, bottom=double_side)

        # 1. Add Main Title Header
        title = f"Manaklay Resort - {report_type.capitalize()} Report ({start_date} to {end_date})"
        worksheet['A1'] = title
        worksheet['A1'].font = title_font
        worksheet.merge_cells('A1:K1')
        worksheet['A1'].alignment = Alignment(horizontal='center', vertical='center')
        worksheet.row_dimensions[1].height = 40
        
        # 2. Style Table Headers (Row 3)
        worksheet.row_dimensions[3].height = 26
        for col_idx in range(1, 12):
            cell = worksheet.cell(row=3, column=col_idx)
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)

        # 3. Format Data Rows (Alignments, Zebra striping, Number/Currency Formats)
        max_row = worksheet.max_row
        for row_idx in range(4, max_row + 1):
            worksheet.row_dimensions[row_idx].height = 20
            is_even = (row_idx % 2 == 0)
            
            for col_idx in range(1, 12):
                cell = worksheet.cell(row=row_idx, column=col_idx)
                cell.font = data_font
                cell.border = data_border
                if is_even:
                    cell.fill = zebra_fill
                
                # Column formatting alignments
                if col_idx == 1:    # Name
                    cell.alignment = Alignment(horizontal='left', vertical='center')
                elif col_idx in [2, 3]:  # Timestamps
                    cell.alignment = Alignment(horizontal='center', vertical='center')
                elif col_idx in [4, 5, 6, 7]:  # Passenger breakdowns
                    cell.alignment = Alignment(horizontal='right', vertical='center')
                    cell.number_format = '#,##0'
                elif col_idx in [8, 9, 10]:  # Details & Flags
                    cell.alignment = Alignment(horizontal='center', vertical='center')
                elif col_idx == 11:  # Currency column
                    cell.alignment = Alignment(horizontal='right', vertical='center')
                    cell.number_format = '₱#,##0.00'

        # 4. Inject Dynamic Summary Totals Row
        summary_row = max_row + 1
        worksheet.row_dimensions[summary_row].height = 24
        
        worksheet.cell(row=summary_row, column=1, value="Total").font = total_font
        worksheet.cell(row=summary_row, column=1).alignment = Alignment(horizontal='left', vertical='center')
        
        for col_idx in range(1, 12):
            cell = worksheet.cell(row=summary_row, column=col_idx)
            cell.border = total_border
            if col_idx > 1:
                cell.font = total_font

        # Dynamic calculations via native Excel calculations
        for col_idx in [4, 5, 6, 7]:
            col_letter = get_column_letter(col_idx)
            cell = worksheet.cell(row=summary_row, column=col_idx)
            cell.value = f"=SUM({col_letter}4:{col_letter}{max_row})"
            cell.number_format = '#,##0'
            cell.alignment = Alignment(horizontal='right', vertical='center')
            
        pay_letter = get_column_letter(11)
        pay_cell = worksheet.cell(row=summary_row, column=11)
        pay_cell.value = f"=SUM({pay_letter}4:{pay_letter}{max_row})"
        pay_cell.number_format = '₱#,##0.00'
        pay_cell.alignment = Alignment(horizontal='right', vertical='center')

        # 5. Fixed Column Width Auto-Adjustment
        for col in worksheet.columns:
            max_len = 0
            col_letter = get_column_letter(col.column)
            for cell in col:
                if cell.row == 1:
                    continue
                val_to_check = str(cell.value or '')
                if val_to_check.startswith('='):
                    val_to_check = " ₱999,999.00 " 
                if len(val_to_check) > max_len:
                    max_len = len(val_to_check)
            
            worksheet.column_dimensions[col_letter].width = max(max_len + 4, 12)

if __name__ == "__main__":
    if len(sys.argv) < 6:
        print("Error: Missing parameters.")
        sys.exit(1)
    generate_report(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
