import sys
import json
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

def generate_report(json_in, excel_out, report_type, start_date, end_date):
    # Load the temporary JSON data generated by PHP
    with open(json_in, 'r') as f:
        data = json.load(f)
    
    # Load into a DataFrame
    df = pd.DataFrame(data)
    
    # Rename columns for a clean presentation
    df.rename(columns={
        'customer_name': 'Customer Name',
        'check_in_time': 'Check-In',
        'check_out_time': 'Check-Out',
        'pax': 'Total Pax',
        'adults': 'Adults',
        'seniors': 'Seniors',
        'children': 'Children',
        'accommodation': 'Accommodation',
        'overnight': 'Overnight',
        'payment_status': 'Status',
        'total_amount': 'Total Payment (PHP)'
    }, inplace=True)

    # Handle missing check-outs
    df['Check-Out'] = df['Check-Out'].fillna('Active')
    
    # Ensure payments are treated as floats
    df['Total Payment (PHP)'] = pd.to_numeric(df['Total Payment (PHP)'], errors='coerce').fillna(0)

    # Write to Excel using the openpyxl engine
    with pd.ExcelWriter(excel_out, engine='openpyxl') as writer:
        # Start writing on row 3 to leave room for the main title
        df.to_excel(writer, index=False, sheet_name='Report Data', startrow=2)
        
        workbook = writer.book
        worksheet = writer.sheets['Report Data']
        
        # --- STYLING ---
        
        # 1. Add Main Title Header
        title = f"Manaklay Resort - {report_type.capitalize()} Report ({start_date} to {end_date})"
        worksheet['A1'] = title
        worksheet['A1'].font = Font(size=14, bold=True, color="1E3A8A")
        worksheet.merge_cells('A1:K1')
        worksheet['A1'].alignment = Alignment(horizontal='center', vertical='center')
        
        # 2. Style Table Headers (Row 3)
        header_fill = PatternFill(start_color="1E3A8A", end_color="1E3A8A", fill_type="solid")
        header_font = Font(color="FFFFFF", bold=True)
        
        for col_num, cell in enumerate(worksheet[3], 1):
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal='center')
            
        # 3. Auto-Adjust Column Widths based on content
        for col_num in range(1, worksheet.max_column + 1):
            column_letter = get_column_letter(col_num)
            max_length = 0
            for row in worksheet.iter_rows(min_col=col_num, max_col=col_num):
                try:
                    if len(str(row[0].value)) > max_length:
                        max_length = len(str(row[0].value))
                except:
                    pass
            adjusted_width = (max_length + 2)
            worksheet.column_dimensions[column_letter].width = adjusted_width

if __name__ == "__main__":
    # Arguments passed from PHP via shell_exec
    generate_report(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])